app:
    resource: "@AppBundle/Controller/"
    type:     annotation

home:
  path: /
  defaults: { _controller: AppBundle:Home:showHome}

login:
  path: /
  defaults: { _controller: AppBundle:Login:login}