app:
    resource: "@AppBundle/Controller/"
    type:     annotation

home:
  path: /
  defaults: { _controller: AppBundle:Home:showHome}

login:
  path: /
  defaults: { _controller: AppBundle:Login:login}

projectlist:
  path: /anlegg
  defaults: { _controller: AppBundle:ProjectList:projectList}

project:
  path: /anlegg/{id}
  defaults: {_controller: AppBundle:Project:show}