app:
    resource: "@AppBundle/Controller/"
    type:     annotation

home:
    path: /
    defaults: { _controller: AppBundle:Home:showHome}

login:
    path: /login
    defaults: { _controller: AppBundle:Login:login}

create_user:
    path:     /register
    defaults: { _controller: AppBundle:User:register } 