app:
    resource: "@AppBundle/Controller/"
    type:     annotation

home:
    path: /
    defaults: { _controller: AppBundle:Home:showHome}

project:
  path: /anlegg
  defaults: { _controller: AppBundle:Project:project}

login:
    path: /login
    defaults: { _controller: AppBundle:Login:login}

logout:
    path: /logout

create_user:
    path:     /register
    defaults: { _controller: AppBundle:User:register } 
