app:
    resource: "@AppBundle/Controller/"
    type:     annotation

home:
    path: /
    defaults: { _controller: AppBundle:Home:showHome}

login:
    path: /login
    defaults: { _controller: AppBundle:Login:login}

logout:
    path: /logout

create_user:
    path:     /register
    defaults: { _controller: AppBundle:User:register } 

post_create_user:
    path:     /registered
    defaults:
      _controller: FrameworkBundle:Template:template
      template: login/post-register.html.twig
      maxAge: 86400
      sharedAge: 86400

aboutus:
    path: /omoss
    defaults: { _controller: AppBundle:AboutUs:show}

projectlist:
  path: /prosjekter
  defaults: { _controller: AppBundle:ProjectList:projectList}

advanced_projectlist:
  path: /prosjektsok
  defaults: { _controller: AppBundle:ProjectList:advancedProjectList}

# Actor functionality

actorlist:
  path: /akteur
  defaults: { _controller: AppBundle:ActorList:show }

# Actor (company) functionality

create_company:
    path:     /selskap/ny
    defaults: {_controller: AppBundle:Company:create }

# TODO
edit_company:
  path: /selskap/rediger/{id}
  defaults: {_controller: AppBundle:Company:edit}
  requirements:
    methods: GET|POST
    id: \d+

# TODO
delete_company:
  path: /selskap/slett/{id}
  defaults: {_controller: AppBundle:Company:delete}
  methods: DELETE
  requirements:
    id: \d+

company:
  path: /selskap/{id}
  defaults: {_controller: AppBundle:Company:show}
  requirements:
    methods: GET|POST
    id: \d+

# Actor (person) functionality

create_person:
    path:     /person/ny
    defaults: {_controller: AppBundle:Person:create }

edit_person:
  path: /person/rediger/{id}
  defaults: {_controller: AppBundle:Person:edit}
  requirements:
    methods: GET|POST
    id: \d+

delete_person:
  path: /person/slett/{id}
  defaults: {_controller: AppBundle:Person:delete}
  methods: DELETE
  requirements:
    id: \d+

person:
  path: /person/{id}
  defaults: {_controller: AppBundle:Person:show}
  requirements:
    methods: GET|POST
    id: \d+

# Projects

project:
  path: /prosjekter/{id}
  defaults: {_controller: AppBundle:Project:show}
  requirements:
    methods: GET|POST
    id: \d+


create_project:
  path:     /prosjekter/ny
  defaults: { _controller: AppBundle:Project:create}

edit_project:
  path:     /prosjekter/rediger/{id}
  defaults: { _controller: AppBundle:Project:edit}
  requirements:
    methods: GET|POST
    id: \d+

delete_project:
  path:     /prosjekter/slett/{id}
  defaults: { _controller: AppBundle:Project:delete}
  methods: DELETE
  requirements:
    id: \d+

create_measure_in_project:
  path:     /prosjekter/{project_id}/tiltak/ny
  defaults: { _controller: AppBundle:Measure:create}
  requirements:
    methods: GET|POST
    project_id: \d+

edit_measure:
  path:     /prosjekter/{project_id}/tiltak/{measure_id}
  defaults: { _controller: AppBundle:Measure:edit}
  requirements:
    methods: GET|POST
    project_id: \d+
    measure_id: \d+

delete_measure:
  path:     /prosjekter/{project_id}/tiltak/{measure_id}/delete
  defaults: { _controller: AppBundle:Measure:delete}
  methods: DELETE
  requirements:
    project_id: \d+
    measure_id: \d+

create_comment_in_project:
  path:     /prosjekter/{project_id}/kommentar/ny
  defaults: { _controller: AppBundle:ProjectComment:create}
  requirements:
    methods: GET|POST
    project_id: \d+

edit_comment:
  path:     /prosjekter/{project_id}/kommentar/{comment_id}
  defaults: { _controller: AppBundle:ProjectComment:edit}
  requirements:
    methods: GET|POST
    project_id: \d+

delete_comment:
  path:     /prosjekter/{project_id}/kommentar/{comment_id}/delete
  defaults: { _controller: AppBundle:ProjectComment:delete}
  methods: DELETE
  requirements:
    project_id: \d+

# Things related to users and profiles

edit:
  path:     /rediger
  defaults: { _controller: AppBundle:EditList:show}

personalprofile:
  path:     /meg
  defaults: { _controller: AppBundle:Profile:showMyProfile}

editpersonalprofile:
  path:     /meg/e
  defaults: { _controller: AppBundle:Profile:editMyProfile}

activate_users:
  path:     /meg/activate
  defaults: { _controller: AppBundle:Profile:activateUsers}

deactivate_users:
  path:     /meg/deactivate
  defaults: { _controller: AppBundle:Profile:deactivateUsers}

promote_editors:
  path:     /meg/promote_editors
  defaults: { _controller: AppBundle:Profile:promoteEditorUsers}

demote_editors:
  path:     /meg/demote_editors
  defaults: { _controller: AppBundle:Profile:demoteEditorUsers}

# View other's profile
publicprofile:
  path: /prof/{id}
  defaults: {_controller: AppBundle:Profile:showProfile}
  requirements:
    methods: GET|POST
    id: \d+

# Edit other's profile
editotherprofile:
  path: /rp/{id}
  defaults: {_controller: AppBundle:Profile:editProfile}
  requirements:
    methods: GET|POST
    id: \d+

# List of users
userlist:
  path: /brukere
  defaults: { _controller: AppBundle:User:showAllUsers}

# Not sure
queryme:
  path:     /meg/qp
  defaults: { _controller: AppBundle:Profile:queryMe}


debug:
  path: /test
  defaults: { _controller: AppBundle:Debug:test}
  requirements:
    methods: GET|POST
