<?php

namespace AppBundle\Repository;

/**
 * ProjectCommentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProjectCommentRepository extends \Doctrine\ORM\EntityRepository
{

}
